language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2.1.1
  - ree
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - openjdk6
script: "bundle exec rake test"
